package com.example.domain;

import java.text.NumberFormat;
import java.util.Objects;

public abstract class Employee {
	
	private static int nextId = 101;
	private int empID;
	private String name = "No_name";
	private String ssn = "A000000000";
	private double salary = 28490;
	protected NumberFormat nf = NumberFormat.getCurrencyInstance();
	
	public Employee(String name, String ssn, double salary) {
		this.empID = nextId++;
		if (name != null && name.trim().length()!=0)
			this.name = name;
		if (ssn.trim().length()!=0)
			this.ssn = ssn;
		if (salary > 28490)
			this.salary = salary;
	}
	
	@Override  //auto-generated by Eclipse
	public int hashCode() {
		return Objects.hash(empID, ssn);
	}

	@Override //auto-generated by Eclipse
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Employee other = (Employee) obj;
		return empID == other.empID && Objects.equals(ssn, other.ssn);
	}

	public int getEmpId() {
		return this.empID;
	}
	public String getName() {
		return this.name;
	}
	public String getSsn() {
		return this.ssn;
	}
	public double getSalary() {
		return this.salary;
	}
	
	public void setName(String name) {
		if (name != null && name.trim().length()!=0)
		this.name = name;
	}
	
	public void raiseSalary(double increase) {
		if(increase > 0)
			this.salary += increase;
	}
	
	
	public void addSkill(String skill) {
		// do nothing
	}

	public boolean addEmployee(Employee employee) {
		// TODO Auto-generated method stub
		return true;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return 
				"-------employee info--------"+"\n"+
				"id: "+ this.empID+"\n"+
				"name: "+ this.name+"\n"+
				"ssn: "+ this.ssn+"\n"+
				"salary: "+ nf.format(this.salary)+"\n";
	}
	
	public abstract double getPay();
	
}
